environment = "production"

[contracts.protected_vault]
address = "0xa390825958F42D7b23A490Be2e29311B12381917"
name = "Ink Vault Demo Protected Vault"

[[contracts.protected_vault.assertions]]
file = "assertions/src/InkVaultDemoAssertions.sol:InkVaultAssetsMatchSharePriceAssertion"

[[contracts.protected_vault.assertions]]
file = "assertions/src/InkVaultDemoAssertions.sol:InkVaultConvertToAssetsOracleSanityAssertion"

[[contracts.protected_vault.assertions]]
file = "assertions/src/InkVaultDemoAssertions.sol:InkVaultCircuitBreakerAssertion"

[contracts.curator_vault]
address = "0xb8719a3d2bea53a739bCA7E47e3E32B25Fe5eB42"
name = "Ink Vault Demo Curator Vault"

[[contracts.curator_vault.assertions]]
file = "assertions/src/InkVaultDemoAssertions.sol:InkCuratorMarketHealthAssertion"
